spring.application.name=farm-market
spring.data.mongodb.uri=${MONGO_URL}
logging.level.org.springframework.security=DEBUG
#
imagekit.publicKey=${IMAGEKIT_PUBLIC_KEY}
imagekit.privateKey=${IMAGEKIT_PRIVATE_KEY}
imagekit.urlEndpoint=${IMAGEKIT_URL_ENDPOINT}

# multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB